"""
Contains useful defines for accessing fields of the stat objects.
"""
DEBUG = False
ID = "id"
NAME = "name"
YEAR = "year"
RANK = "rank"
MIN_PLAYERS = "min_players"
MAX_PLAYERS = "max_players"
COMPLEXITY = "complexity"
RATING = "rating"
NUM_RATINGS = "number_of_ratings"
NUM_COMMENTS = "number_of_comments"
DESIGNERS = "designers"
PUBLISHERS = "publishers"
ARTISTS = "artists"

WEEK = "week"
P1 = "Johannes"
P2 = "Sunniva"
VERDICT = "verdict"
KEEP= "KEEP"
CULL = "CULL"
